# Generated by Django 4.2.3 on 2023-07-08 15:24

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsultingInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part",
                    django_mysql.models.ListCharField(
                        models.CharField(max_length=10),
                        max_length=100,
                        size=None,
                        verbose_name="지원파트",
                    ),
                ),
                ("company_name", models.CharField(max_length=16, verbose_name="회사명")),
                ("name", models.CharField(max_length=16, verbose_name="이름")),
                ("phone", models.CharField(max_length=16, verbose_name="연락처(휴대폰)")),
                ("business", models.CharField(max_length=16, verbose_name="업종")),
                ("sales", models.CharField(max_length=16, verbose_name="매출")),
                ("inquiry", models.TextField(verbose_name="내용")),
                ("reg_ts", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "컨설팅 요청",
                "verbose_name_plural": "컨설팅 요청 목록",
                "db_table": "consulting",
            },
        ),
        migrations.CreateModel(
            name="PartnershipInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=16, verbose_name="연락처")),
                ("email", models.EmailField(max_length=32, verbose_name="이메일")),
                ("inquiry", models.TextField(verbose_name="제안내용")),
                ("reg_ts", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "제휴문의",
                "verbose_name_plural": "제휴문의 목록",
                "db_table": "partnership",
            },
        ),
    ]
