# Generated by Django 4.2.3 on 2023-07-25 11:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultinginquiry",
            name="part01",
            field=django_mysql.models.ListCharField(
                models.CharField(max_length=10),
                default="",
                null=True,
                max_length=100,
                size=None,
                verbose_name="자금유치 파트",
            ),
        ),
        migrations.AddField(
            model_name="consultinginquiry",
            name="part02",
            field=django_mysql.models.ListCharField(
                models.CharField(max_length=10),
                default="",
                null=True,
                max_length=100,
                size=None,
                verbose_name="브랜딩/마케팅 파트",
            ),
        ),
        migrations.AddField(
            model_name="consultinginquiry",
            name="part03",
            field=django_mysql.models.ListCharField(
                models.CharField(max_length=10),
                default="",
                null=True,
                max_length=100,
                size=None,
                verbose_name="개발 파트",
            ),
        ),
        migrations.AlterField(
            model_name="consultinginquiry",
            name="part",
            field=django_mysql.models.ListCharField(
                models.CharField(max_length=10),
                default="",
                null=True,
                max_length=100,
                size=None,
                verbose_name="(제거예정) 파트",
            ),
        ),
    ]
