# Generated by Django 4.2.4 on 2023-08-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiry", "0002_consultinginquiry_part01_consultinginquiry_part02_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultinginquiry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="consultinginquiry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="partnershipinquiry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="partnershipinquiry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.RunSQL(
            """
            UPDATE consulting SET created_at = reg_ts, updated_at = reg_ts WHERE 1=1
            """
        ),
        migrations.RunSQL(
            """
            UPDATE partnership SET created_at = reg_ts, updated_at = reg_ts WHERE 1=1
            """
        ),
    ]
