# Generated by Django 4.2.4 on 2023-08-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionmodel_inherit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionmodel',
            options={'ordering': ['ordering'], 'verbose_name': '구독모델', 'verbose_name_plural': '구독모델'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionmodelservice',
            options={'ordering': ['ordering'], 'verbose_name': '구독모델 서비스', 'verbose_name_plural': '구독모델 서비스목록'},
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='ordering'),
        ),
        migrations.AddField(
            model_name='subscriptionmodelservice',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='ordering'),
        ),
    ]
