# Generated by Django 4.2.4 on 2023-12-31 11:27

import besafe.models.contents
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('banner_img', models.ImageField(upload_to=besafe.models.contents.upload_to_hero, verbose_name='배너이미지')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('subtitle', models.CharField(max_length=128, verbose_name='부제목')),
                ('button_url', models.URLField(blank=True, max_length=256, null=True, verbose_name='자세히 보기 URL')),
            ],
            options={
                'verbose_name': '콘텐츠 - 메인[Hero]',
                'verbose_name_plural': '콘텐츠 - 메인[Hero]',
                'db_table': 'contents_hero',
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
