# Generated by Django 4.2.4 on 2023-12-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentshero',
            name='subtitle',
            field=models.CharField(max_length=32, verbose_name='부제목'),
        ),
    ]
