# Generated by Django 4.2.4 on 2023-12-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0004_alter_contentshero_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentshero',
            name='button_text',
            field=models.CharField(default='자세히 보기', max_length=32, verbose_name='버튼 텍스트'),
        ),
        migrations.AlterField(
            model_name='contentshero',
            name='button_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='버튼 URL'),
        ),
    ]
