# Generated by Django 4.2.4 on 2023-12-31 17:08

import besafe.models.contents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0005_contentshero_button_text_and_more'),
    ]


    operations = [
        migrations.CreateModel(
            name='ContentsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('banner_img', models.ImageField(upload_to=besafe.models.contents.upload_to_news, verbose_name='배너이미지')),
                ('company', models.CharField(max_length=128, verbose_name='회사')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('subtitle', models.CharField(max_length=128, verbose_name='부제목')),
                ('button_text', models.CharField(default='자세히 보기', max_length=32, verbose_name='버튼 텍스트')),
                ('button_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='버튼 URL')),
            ],
            options={
                'verbose_name': '콘텐츠 - 메인[News]',
                'verbose_name_plural': '콘텐츠 - 메인[News]',
                'db_table': 'contents_news',
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
