# Generated by Django 4.2.4 on 2023-12-31 18:20

import besafe.models.contents
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0006_contentsnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentsCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('banner_img', models.ImageField(upload_to=besafe.models.contents.upload_to_customer, verbose_name='로고이미지')),
                ('company', models.CharField(max_length=128, verbose_name='회사명')),
            ],
            options={
                'verbose_name': '콘텐츠 - 메인[Customers]',
                'verbose_name_plural': '콘텐츠 - 메인[Customers]',
                'db_table': 'contents_customers',
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
