# Generated by Django 4.2.4 on 2023-12-31 23:18

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0008_tag_contentsportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=128, verbose_name='태그 제목'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.URLField(verbose_name='태그 URL'),
        ),
    ]
