# Generated by Django 4.2.4 on 2024-01-01 13:36

import besafe.models.contents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0009_alter_tag_title_alter_tag_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128, verbose_name='역할')),
            ],
        ),
        migrations.RenameModel(
            old_name='ContentsCustomers',
            new_name='ContentsCustomer',
        ),
        migrations.AlterModelOptions(
            name='contentscustomer',
            options={'ordering': ['ordering'], 'verbose_name': '콘텐츠 - 메인[Customer]', 'verbose_name_plural': '콘텐츠 - 메인[Customer]'},
        ),
        migrations.CreateModel(
            name='ContentsTeammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('banner_img', models.ImageField(upload_to=besafe.models.contents.upload_to_portfolio, verbose_name='이미지')),
                ('position', models.CharField(max_length=128, verbose_name='직책')),
                ('name', models.CharField(max_length=128, verbose_name='이름')),
                ('roles', models.ManyToManyField(to='besafe.roles', verbose_name='역할')),
            ],
            options={
                'verbose_name': '콘텐츠 - 비세이프 소개[Teammate]',
                'verbose_name_plural': '콘텐츠 - 비세이프 소개[Teammate]',
                'db_table': 'contents_teammate',
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
