# Generated by Django 4.2.4 on 2024-01-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0010_roles_rename_contentscustomers_contentscustomer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
