# Generated by Django 4.2.4 on 2024-01-01 14:09

import besafe.models.contents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0011_rename_roles_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsteammate',
            name='banner_img',
            field=models.ImageField(upload_to=besafe.models.contents.upload_to_teammate, verbose_name='이미지'),
        ),
    ]
