# Generated by Django 4.2.4 on 2024-01-01 17:33

import besafe.models.contents
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0012_alter_contentsteammate_banner_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentsConsulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('profile_img', models.ImageField(upload_to=besafe.models.contents.upload_to_consulting, verbose_name='프로필 이미지')),
                ('profile_company', models.CharField(max_length=32, verbose_name='업체명')),
                ('profile_name', models.CharField(max_length=32, verbose_name='담당자 이름')),
                ('consulting_title', models.CharField(max_length=32, verbose_name='컨설팅 제목')),
                ('consulting_description', models.CharField(max_length=128, verbose_name='컨설팅 내용')),
                ('consulting_items', django_mysql.models.ListCharField(models.CharField(max_length=16), max_length=102, size=6, verbose_name='컨설팅 항목')),
                ('review_title', models.CharField(max_length=32, verbose_name='리뷰 제목')),
                ('review_contents', models.CharField(max_length=128, verbose_name='리뷰 제목')),
            ],
            options={
                'verbose_name': '콘텐츠 - 컨설팅[Consulting]',
                'verbose_name_plural': '콘텐츠 - 컨설팅[Consulting]',
                'db_table': 'contents_consulting',
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
