# Generated by Django 4.2.4 on 2024-01-01 18:12

import besafe.models.contents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0014_alter_contentsnews_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsportfolio',
            name='thumbnail_img',
            field=models.ImageField(null=True, upload_to=besafe.models.contents.upload_to_portfolio, verbose_name='대표 이미지'),
        ),
        migrations.AlterField(
            model_name='contentsportfolio',
            name='banner_img',
            field=models.ImageField(upload_to=besafe.models.contents.upload_to_portfolio, verbose_name='배너 이미지'),
        ),
    ]
