# Generated by Django 4.2.8 on 2024-01-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0016_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='파일명'),
        ),
    ]
