# Generated by Django 4.2.8 on 2024-01-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0017_media_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentshero',
            name='button_target',
            field=models.CharField(default='_self', max_length=32, verbose_name='버튼 target'),
        ),
    ]
