# Generated by Django 4.2.8 on 2024-01-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besafe', '0018_contentshero_button_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsportfolio',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='contentsportfolio',
            name='detail',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='사이트 바로가기'),
        ),
        migrations.AlterField(
            model_name='contentsportfolio',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='besafe.tag', verbose_name='태그'),
        ),
    ]
